version: "3"

services:
  deluge:
    image: redirect_app
    container_name: redirect_deluge_app
    restart: unless-stopped
    ports:
      - ${DELUGE_PORT}:80
    environment:
      - TARGET_URL=${DELUGE_TARGET_URL}
